In [31]:
grid = [ [5,3,0,0,7,0,0,0,0],
         [6,0,0,1,9,5,0,0,0],
         [0,9,8,0,0,0,0,6,0],
         [8,0,0,0,6,0,0,0,3],
         [4,0,0,8,0,3,0,0,1],
         [7,0,0,0,2,0,0,0,6],
         [0,6,0,0,0,0,2,8,0],
         [0,0,0,4,1,9,0,0,5],
         [0,0,0,0,8,0,0,7,9]  ]

In [32]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [33]:
import numpy as np

In [34]:
print (np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [35]:
# x =4 
# y= 4
# x0 = round(4/3) =1 ,    1 *3 = 3
#y0 = round(4/3) =1 ,     1*3 =3


In [36]:
def possible(y,x,n):
    global grid
    #checks for similarly occuring number on x axis
    for i in range (0,9):
        if grid[y][i] == n:
            return False
        
    #This for loop checks for similarly occuring number on the y axis
    for i in range (0,9):
        if grid[i][x] == n:
            return False

    #Checks for surrounding 3x3 square for a similar occuring number
    xSquareGrid = (x//3) * 3
    ySquareGrid = (y//3) * 3
    for i in range (0,3):
        for j in range (0,3):
            if grid[ySquareGrid+i][xSquareGrid +j]== n:
                return False
    return True

In [40]:
def solveSudoku():
    global grid
    for y in range(9):
        for x in range (9):
            if grid[y][x]== 0:
                for n in range(1,10):
                    
                    #Calls the previous possible() function to check if a number in the range(1,10) can replace the zero,
                    # and then replaces it if True.
                    if possible(y,x,n):
                        grid[y][x] = n
                        #Recursively calls it self to backtrack.
                        solveSudoku()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    print('Done !')
                

In [41]:
solveSudoku()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Done !
